export const pathNames = {
  HOME: "/",
  STORE: "/store",
  ABOUT_US: "/about-us",
  BLOGS: "/blogs",
  CONTACT: "/contact",
  ORDER: "/account_orders",
  ORDER_DETAIL: "/account_orders/:id",
  SHOP_ORDER_COMPLETE: "/shop_order_complete",
  PAYMENT_POLICY: "/policies/payment",
  COMPLAINT_POLICY: "/policies/complaint",
  SHIPPING_AND_DELIVERY_POLICY: "/policies/shipping-and-delivery",
  RETURN_AND_REFUND_POLICY: "/policies/return-refund",
  INSPECTION_POLICY: "/policies/inspection",
  PRIVATE_POLICY: "/policies/private",
};

export const pathNameLabel: any = {
  "": "Trang chủ",
  store: "Cửa hàng",
  "about-us": "Về Double Fish",
  blogs: "Bài viết",
  contact: "Liên hệ",
  account_edit: "Cập nhật tài khoản",
  account_orders: "Quản lý đơn hàng",
  account_edit_address: "Quản lý địa chỉ",
  account_wishlist: "Sản phẩm yêu thích",
  shop_checkout: "Đặt hàng",
  shop_cart: "Giỏ hàng",
  shop_order_complete: "Đặt hàng",
};
